runtime: python27
service: front-end
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/front-end/index.html
    upload: dist/front-end/index.html
  - url: /
    static_dir: dist/front-end

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE